# Generated by Django 2.0.4 on 2018-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180430_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Bio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=None),
        ),
    ]
