# Generated by Django 2.0.6 on 2018-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
